"""empty message

Revision ID: 54a4564d0889
Revises: 7e866ac1e440
Create Date: 2023-03-21 09:08:12.992495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54a4564d0889'
down_revision = '7e866ac1e440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_cleaning_date')
        batch_op.create_index(batch_op.f('ix_cleaning_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_cleaning_timestamp'))
        batch_op.create_index('ix_cleaning_date', ['date'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
