"""empty message

Revision ID: 7e866ac1e440
Revises: ecf7cd54069c
Create Date: 2023-03-20 19:20:09.670142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e866ac1e440'
down_revision = 'ecf7cd54069c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bemerkung', sa.String(length=255), nullable=True))
        batch_op.drop_index('ix_cleaning_bemerkunng')
        batch_op.create_index(batch_op.f('ix_cleaning_bemerkung'), ['bemerkung'], unique=False)
        batch_op.drop_column('bemerkunng')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bemerkunng', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_cleaning_bemerkung'))
        batch_op.create_index('ix_cleaning_bemerkunng', ['bemerkunng'], unique=False)
        batch_op.drop_column('bemerkung')

    # ### end Alembic commands ###
